services:
  - type: web
    name: bodega-wms
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build:frontend
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20.18.1"
       - key: npm_config_build_from_source 
        value: "true"
